// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ModelPredictService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class ModelPredictServiceHandler : virtual public ModelPredictServiceIf {
 public:
  ModelPredictServiceHandler() {
    // Your initialization goes here
  }

  void predictPb(std::string& _return, const std::string& model_key, const std::string& request_msg) {
    // Your implementation goes here
    printf("predictPb\n");
  }

  double predict(const std::map<std::string, std::string> & row) {
    // Your implementation goes here
    printf("predict\n");
  }

  void predictList(std::vector<double> & _return, const std::vector<std::map<std::string, std::string> > & rows) {
    // Your implementation goes here
    printf("predictList\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<ModelPredictServiceHandler> handler(new ModelPredictServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new ModelPredictServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

