/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "model_predict_constants.h"



const model_predictConstants g_model_predict_constants;

model_predictConstants::model_predictConstants() {
}



