/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef model_predict_CONSTANTS_H
#define model_predict_CONSTANTS_H

#include "model_predict_types.h"



class model_predictConstants {
 public:
  model_predictConstants();

};

extern const model_predictConstants g_model_predict_constants;



#endif
