/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nx_adp_constants.h"



const nx_adpConstants g_nx_adp_constants;

nx_adpConstants::nx_adpConstants() {
}



