/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nx_adp_CONSTANTS_H
#define nx_adp_CONSTANTS_H

#include "nx_adp_types.h"



class nx_adpConstants {
 public:
  nx_adpConstants();

};

extern const nx_adpConstants g_nx_adp_constants;



#endif
